# Generated by Django 5.1.2 on 2024-10-20 10:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Can_cancel_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_person', to='media.image'),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomeActors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_home_actors', to='event.person')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
