# Generated by Django 5.1.2 on 2024-10-21 14:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_can_cancel_ticket_event_rules_person_biography_and_more'),
        ('place', '0004_externalhallid_externalplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 21, 14, 58, 21, 405704, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_fee', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('vat', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('start_at', models.DateTimeField()),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.IntegerField(blank=True, null=True)),
                ('starred_text', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule', to='event.event')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_schedule', to='place.place')),
                ('place_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_hall_schedule', to='place.placehall')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(choices=[('gishe', 'Gishe'), ('samfa', 'SAMFA')], max_length=5)),
                ('external_id', models.CharField(max_length=30)),
                ('external_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(choices=[('gishe', 'Gishe'), ('samfa', 'SAMFA')], max_length=5)),
                ('external_id', models.CharField(max_length=30)),
                ('external_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='externals', to='event.eventschedule')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventschedule',
            index=models.Index(fields=['event', 'start_at'], name='event_event_event_i_81edaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalevent',
            unique_together={('driver', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='externalschedule',
            unique_together={('driver', 'external_id')},
        ),
    ]
