# Generated by Django 5.1.2 on 2024-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_person_created_at_person_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
