# Generated by Django 5.1.2 on 2024-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_genre_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
