# Generated by Django 5.1.2 on 2024-10-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='release_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
