# Generated by Django 5.1.2 on 2024-10-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event__year_event_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='_year',
            new_name='production_year',
        ),
    ]
