# Generated by Django 5.1.2 on 2024-10-19 12:17

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('geo', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('place_code', models.IntegerField(default=None, null=True)),
                ('rate', models.FloatField(default=0)),
                ('rate_count', models.BigIntegerField(default=0)),
                ('telegram_id', models.URLField(blank=True, null=True)),
                ('instagram_id', models.URLField(blank=True, null=True)),
                ('facility', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('elevator', 'Elevator'), ('parking', 'Parking'), ('buffet', 'Buffet'), ('restaurant', 'Restaurant'), ('carwash', 'Carwash'), ('card_reader', 'CardReader'), ('print_ticket', 'PrintTicket'), ('disabled_access', 'DisabledAccess'), ('atm', 'ATM'), ('coffee_shop', 'CoffeeShop'), ('book_shop', 'BookShop'), ('foodcourt', 'FoodCourt'), ('internet', 'Internet')], max_length=50), blank=True, default=list, null=True, size=None)),
                ('halls_count', models.IntegerField(blank=True, default=0, null=True)),
                ('seats_count', models.IntegerField(default=0)),
                ('gishe_count', models.IntegerField(default=0)),
                ('kiosk_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('access_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('telephone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, null=True, size=None)),
                ('sales_capacity', models.IntegerField(default=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('verified', models.BooleanField(default=False)),
                ('established_at', models.DateTimeField(blank=True, null=True)),
                ('renovated_at', models.DateTimeField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('online_fee', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('vat', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_place', to='geo.city')),
                ('threads', models.ManyToManyField(blank=True, related_name='thread_places', to='comment.thread')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_thumbnail', to='media.image')),
            ],
        ),
    ]
