# Generated by Django 5.1.2 on 2024-10-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalHallId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(choices=[('gishe', 'Gishe'), ('samfa', 'SAMFA')], max_length=5)),
                ('external_id', models.CharField(max_length=10)),
                ('external_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='place.placehall')),
            ],
            options={
                'unique_together': {('driver', 'external_id'), ('driver', 'hall')},
            },
        ),
        migrations.CreateModel(
            name='ExternalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(choices=[('gishe', 'Gishe'), ('samfa', 'SAMFA')], max_length=5)),
                ('external_id', models.CharField(max_length=10)),
                ('external_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='place.place')),
            ],
            options={
                'unique_together': {('driver', 'external_id'), ('driver', 'place')},
            },
        ),
    ]
