# Generated by Django 5.1.2 on 2024-10-15 10:12

import media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('desktop', models.ImageField(upload_to=media.models.desktop_image_directory_path)),
                ('desktop_url', models.URLField(blank=True, null=True)),
                ('mobile', models.ImageField(blank=True, null=True, upload_to=media.models.mobile_image_directory_path)),
                ('mobile_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('desktop', models.FileField(upload_to=media.models.desktop_video_directory_path)),
                ('desktop_url', models.URLField(blank=True, null=True)),
                ('mobile', models.FileField(blank=True, null=True, upload_to=media.models.mobile_video_directory_path)),
                ('mobile_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
